# Generated by Django 2.2.1 on 2020-02-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheori', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotimage',
            options={'verbose_name': '観光スポット画像データ', 'verbose_name_plural': '観光スポット画像データ'},
        ),
    ]
